title: Project
pages: false
files: 
  sortable: true
  fields:
    caption:
      label: Caption
      type: text
    sizing:
      label: Size
      type: radio
      default: big
      options:
        big: Big
        small: Small
fields:
  title:
    label: Title
    type:  text
  sizing:
    label: Image Size
    type: radio
    options:
      big: Big
      small: Small
  description:
    label: Description
    type: textarea

      

