title: Project
pages: false
files: 
  sortable: true
  fields:
    caption:
      label: Caption
      type: text
fields:
  title:
    label: Title
    type:  text
  sizing:
    label: Image Size
    type: radio
    options:
      big: Big
      small: Small
  description:
    label: Description
    type: textarea

      

