title: Project
pages: false
files: 
  sortable: true
  fields:
    insert:
      label: Text Description
      type: textarea
    sizing:
      label: Size
      type: radio
      default: big
      options:
        big: Big
        small: Small
fields:
  title:
    label: Title
    type:  text
  sizing:
    label: Image Size
    type: radio
    options:
      big: Big
      small: Small

      

